"""
Django settings for dev project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
path = '/root/dev/config/django_secret_key.txt'
f = open(path, "r")
SECRET_KEY = f.read()
f.close()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.pinoylearnpython.com', '172.104.190.249']

# Application definition
INSTALLED_APPS = [
	'myroot',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'django.contrib.humanize',
	'django.contrib.sites',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dev.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
				'myroot.global_config.global_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'dev.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
	'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': '/root/dev/config/default.cnf',
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ASGI_APPLICATION should be set to your outermost router
ASGI_APPLICATION = 'dev.routing.application'

# Channels-specific settings
redis_host = os.environ.get('localhost')

CHANNEL_LAYERS = {
    "default": {
        # This example app uses the Redis channel layer implementation channels_redis
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(redis_host, 6379)],
            "prefix": "PLP",
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# *******************************************
# My custom configurations
# *******************************************
# For base url, include "/" at the end
BASE_URL = 'https://dev.pinoylearnpython.com/'

# For app labels section here
APP_LABEL_MYROOT = 'myroot'

# Common Site Information here
SITE_SHORT_NAME = "{{ PLP }}"
SITE_FULL_NAME = "Pinoy Learn Python"
SITE_YEAR_STARTED = "2018"
SITE_URL_HOME = "https://pinoylearnpython.com"
SITE_SLOGAN = SITE_FULL_NAME + " - To Help Filipino Students to Learn Python!"
SITE_CONTACT_US = "https://pinoylearnpython.com/get-in-touch-with-me/"

# Minimum characters for search
MIN_CHARS_SEARCH = 3

# App Common Information
APP_EMAIL_FROM = 'support@pinoylearnpython.com'
APP_URL_TOP_LOGO = BASE_URL + 'static/assets/images/PinoyLearnPython-PLP.png'
APP_USER_AUTH_RE_ACCESS_LOGIN_PAGE = 'helloworld'

# Default Avatar
DEFAULT_AVATAR = STATIC_URL + 'assets/images/avatar.png'

# Google reCAPTCHA v3 api keys
GRECAP_SITE_KEY = '6Lfk1ZAUAAAAAAqn3hiZ41ROoZ3xvJNKJFDuV-rH'

path_sk = '/root/dev/config/GRECAP_SECRET_KEY.txt'
read_sk = open(path_sk, "r")
GRECAP_SECRET_KEY = read_sk.read()
read_sk.close()

GRECAP_VERIFY_URL = 'https://www.google.com/recaptcha/api/siteverify'

# MY OWN PASSWORD SETTINGS:
MIN_PASS_LENGTH = 8
PASSWORD_RESET_TIMEOUT_DAYS = 1

# User Login Options
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'dashboard'

# SMTP Server Settings
path_email = '/root/dev/config/email_pass.txt'
fem = open(path_email, "r")
EMAIL_HOST_PASSWORD = fem.read()
fem.close()

EMAIL_HOST = 'smtp.dreamhost.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'notify@xn--webppapps-z79d.com'
DEFAULT_FROM_EMAIL = 'support@pinoylearnpython.com'
EMAIL_USE_SSL = True

# SMTP for Production
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Enable the defaut site framework
SITE_ID = 1
